### ISSUE TITLE
UX: What is the user journey while working with a Todo item?

### ISSUE THREAD

**Issue by spencerreeves** [SAKA-club/todo#1]
In order to create a UI for a Todo Item, we need to know the flow of working with a Todo item. The goal of this ticket is to think through the following questions and add a high fidelity description so that we can mock out the UI. 

- [x] - How will a user view a Todo Item?
- [x] - How will a user create Todo Item?
- [x] - How will a user edit a Todo Item?
- [x] - How will a user save a Todo Item?
- [x] - How will a user delete a Todo item?

**Comment by spencerreeves** [comment]
### How will a user view a Todo Item?
A Todo item will have two different views - collapsed and expanded. In the collapsed version, we will show whether the item is prioritized, the title of the item, and if it is done (this will be removed in a later feature when Done items are moved to a different part of the app). The expanded version will show non editable widgets for the title, body, completion date, whether the item is done, and whether the item is prioritized. The expanded version will have the ability to edit the the Todo Item, which will make all fields editable. To change back to the expanded version, the user will have to choose between saving their changes or canceling their changes.

**Comment by klooopmoo** [comment]
**How will a user edit a Todo Item?**

The user should be only able to create a Todo Item when they are in the list of Todo items not while they are in a specific Todo item or while they are editing. When creating a Todo item the user must be able to input a Title as we expect the title to not be empty.  The user should be able to input a body where the user can include any acceptable formatted text. The user should be able to set priority and be able to set a completion date. The body, priority and completion date can be left blank if the user wishes. Finally the user should have a way to save or delete the Todo item. Upon creating the Todo item the user will see the Todo Item in an expandable view.


Previous post may use as reference: 
//
When the user is in the list of Todo items the user will have an option of creating a new Todo item via a widget or button on the lower right of the screen. Upon pressing the button the user will be shown an empty Todo item. On the top the user will be asked to fill in a Title. There will be a body field right below the title where the user can include any acceptable formatted text.  The user will have a widget that will prompt a calendar so they can pick a completion date if they wish.  A priority widget will be on the top right that once clicked will make this Todo item a priority. The done widget will also be clickable.   At this point the user can click on the save button located towards the bottom as an item can be saved with the Title. If no title is filled, the save button will not be clickable (In later features the save button will not be require). Upon creating the Todo item the user will see the Todo Item in an expandable view.

**Comment by klooopmoo** [comment]
**How will a user edit a Todo Item?**

The user will only be able to edit an item if they are in the expandable view of a Todo item. The user will be allowed to edit each editable field. If they click over the title, date, body, priority or done, the user will be allowed to edit each of the fields respectfully.  Upon completing any edit for each field, a save button will appear  (when auto save is implement the user will not have a save button). If the user wishes to edit all fields the user will have the option with an edit widget.. This will allow them to edit all fields and will resemble how a user creates a Todo item.

**Comment by klooopmoo** [comment]
**How will a user save a Todo Item?**


In V1 the user will save a Todo item via a save button/widget. The widget will only be clickable if the user include some text in the title.  In V2 the user will have to click on a back widget. Any text in any fields will automatically be saved. If the user does not fill the title the back button will not be able to be clicked (in later versions we can possibly save Todo items as drafts?).

**Comment by klooopmoo** [comment]
**How will a user delete a Todo item?**


A user will be able to delete Todo items in the collapsed and expanded view. In the collapsed view the user should be able to delete the item while hovering over the item. If the user is in the expanded view the user will have to click to edit the item. In the edit item screen they should have the ability to delete the item. Upon deleting the item the user will be brought back to the list of Todo items that have not been deleted or completed.
