### ISSUE TITLE
UI: Mock out todo item views

### ISSUE THREAD

**Issue by spencerreeves** [SAKA-club/todo#2]
We need the UI for the following pieces. Please use the following Figma file: https://www.figma.com/file/3qwAJgEMySCRAOq4ZygXZb/TODO?node-id=701%3A140

Story Board:
- Is this supposed to be used on mobile? Web? Both?
  - We are going to focus on web-first. Mobile may come in a later rollout, but not V1
- Who is the target audience?
  - Students and workers. Someone who wants to set goals for themselves, doesn't necessarily need to be in the workforce, but a self driven individual. Looking at a younger population because they are more tech savvy than an older population - young adults to mid age adults in their 20s - 30s. The app is meant to be for personal use. Described as a personality, it is helpful, reliable, dependable, encouraging, discreet, optimistic, friendly, accessible, and modern. For your own personal growth.

https://colormatters.com/color-and-design/basic-color-theory
- https://thisisneat.com.au/
  - Liked the color palette, seems friendly and inviting, but also professional
  - Rounded buttons, material design, small font
- https://www.wattpad.com/
  - simple, whimsical branding, consistent, clean, color palette works well together
  - fonts are nice
  - https://fonts.google.com/specimen/Nunito
  - https://fonts.google.com/specimen/Source+Sans+Pro
- https://wpsetup.org/
  - Likes the characters, simple design. Doesn't like the amount of space left white.
- https://www.buggybix.com.au
  - fun

- #13 
- [ ] View of a list of Todo items (collapsed)
- [ ] View of an expanded Todo item
- [ ] View of a Todo item in edit mode
- [ ] View of how we start editing a Todo item
- [ ] View of the transition form expanded Todo Item to edit mode
- [ ] View of how we save a Todo Item
- [ ] View of the transition from edit mode to expanded Todo item (saved/cancelled)
- [ ] View of how we delete a Todo Item
- [ ] View of how we mark a Todo Item as prioritized
- [ ] View of the transition from expanded Todo view to the list of items

**Comment by spencerreeves** [comment]
Resource for designs:
- https://dribbble.com/
- https://www.figma.com/

Icons:
- https://thenounproject.com/

Colors:
- https://coolors.co/
- https://hexcolor.co/palette-generator

Fonts:
- https://fonts.google.com/
