### ISSUE TITLE
Add todo item view

### ISSUE THREAD

**Issue by spencerreeves** [SAKA-club/todo#24]
For this ticket:
- [x] Add two fonts, Nunito light/medium and Source Sans Pro Regular
- [x] Create a new file item.dart. In that file, create a class called item, and add the [JsonSeralizable](https://pub.dev/packages/json_serializable) notation. This will generate a file called item.g.dart. To generate this, run `flutter pub run build_runner build`
- [x] Create a new file item_view.dart with a stateless widget called ItemView. This will be responsible for all the presentation layer logic, including how to size the item. See [figma](https://www.figma.com/file/3qwAJgEMySCRAOq4ZygXZb?node-id=911:325#236260865) and this screen shot for more details ![Screen Shot 2022-07-27 at 2 34 55 PM](https://user-images.githubusercontent.com/4575753/181376745-d2f7a54d-d28b-4dd1-b441-30536afe08df.png)

**Comment by spencerreeves** [comment]
To show ellipses, look at this SO post: https://stackoverflow.com/questions/44579918/flutter-wrap-text-on-overflow-like-insert-ellipsis-or-fade

**Comment by klooopmoo** [comment]
review and follow steps [setting-up-flutter](https://dash-overflow.net/articles/getting_started/)

**Comment by klooopmoo** [comment]
How to use the generated code from [JSONSerializable](https://medium.flutterdevs.com/automatic-generate-json-serializable-in-flutter-4c9d2d23ed88)

**Comment by klooopmoo** [comment]
Accidently pushed to main! Please review main
