### ISSUE TITLE
Add todo list view

### ISSUE THREAD

**Issue by spencerreeves** [SAKA-club/todo#25]
For this ticket:
- [x] Create a new file item_list.dart. In that file, create a class called ItemList, and add the [JsonSeralizable](https://pub.dev/packages/json_serializable) notation. This will generate a file called item_list.g.dart. To generate this, run `flutter pub run build_runner build`. The class properties should be similar to the data we get back when we get all items from our API.
- [ ] Create a new file, item_list_provider.dart. In that file, we will store the ephemeral state using the [provider](https://pub.dev/packages/provider) package. This file will hold the logic for calling our API.
- [ ] Create a new file item_list_view.dart with a stateless widget called ItemListView. This will be responsible for all the presentation layer logic. Use Flutter's builtin widget [ListView](https://api.flutter.dev/flutter/widgets/ListView-class.html) to create the list of todo items. The itemBuilder should return our [item](https://github.com/SAKA-club/todo/issues/24) widget. See [figma](https://www.figma.com/file/3qwAJgEMySCRAOq4ZygXZb?node-id=917:258#237811179) and this screen shot for more details <img width="367" alt="Screen Shot 2022-07-29 at 4 08 13 PM" src="https://user-images.githubusercontent.com/4575753/181858549-216e6c3e-31ef-4842-a60a-1be641d6938a.png">

**Comment by klooopmoo** [comment]
Per our standup we are not doing the first task because we are only returning an array of Items
